best2.pth:
  build_time: 2021-01-18-14-32-30
  labels:
    blocked: 117
    free: 112
  loader:
    batch_size: 8
    num_workers: 0
    shuffle: true
  train:
    accuracy: 1.0
    epochs: 10
    learning_rate: 0.001
    model: alexnet
    momentum: 0.09
    train_time: 310.81
    use_cuda: true
