best_steering_model_xy.pth:
  build_time: 2021-01-27-13-23-50
  loader:
    batch_size: 16
    num_workers: 4
    shuffle: true
  train:
    epochs: 30
    model: resnet18
    optimizer:
      betas:
      - 0.9
      - 0.999
      eps: 1.0e-08
      learning_rate: 0.001
      name: Adam
      weight_decay: 0
    test_loss: 0.04790143668651581
    train_loss: 0.018080394715070724
    train_time: 318.9
    use_cuda: true
  purpose: regression
